
/*
 * 
 */

package com.txu.registrationapp.soapservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 17 04:03:38 CDT 2016
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UtilityPlanServiceImpl", 
                  wsdlLocation = "file:/C:/BCJMay16/GitRepo/TXUCustomerRegistration/src/main/resources/txuServices.wsdl",
                  targetNamespace = "http://soap.service.registration.txu.com/") 
public class UtilityPlanServiceImpl extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soap.service.registration.txu.com/", "UtilityPlanServiceImpl");
    public final static QName UtilityPlanServiceImplPort = new QName("http://soap.service.registration.txu.com/", "UtilityPlanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BCJMay16/GitRepo/TXUCustomerRegistration/src/main/resources/txuServices.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/BCJMay16/GitRepo/TXUCustomerRegistration/src/main/resources/txuServices.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UtilityPlanServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityPlanServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UtilityPlanServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UtilityPlanServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort() {
        return super.getPort(UtilityPlanServiceImplPort, UtilityPlanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UtilityPlanServiceImplPort, UtilityPlanService.class, features);
    }

}
